#+----------------------------------------------------------+
#| Plugin: BookShelf                                        |
#| Created by: Pew446                                       |
#| DevBukkit: http://dev.bukkit.org/server-mods/bookshelf/  |
#+----------------------------------------------------------+

rows: 2

permissions:
    allow_book: true
    allow_book_and_quill: true
    allow_signed: true 