name: BookShelf
main: me.Pew446.BookShelf.BookShelf
version: 1.1.1
description: Allows players to store books in bookshelves.
commands:
   bookshelf:
      description: Sets target bookshelf to never run out of books.
      usage: /<command>
      aliases: ['bs']
      permission: bookshelf
      permission-message: You don't have permission for that command!
permissions:
    bookshelf.*:
        description: Gives all permissions of BookShelf
        children:
            bookshelf.bs: true
    bookshelf.bs:
        description: Allows player to make bookshelf never stop giving books
        default: op
